#pragma once
#include "aOpenGL/app.h"
#include "aOpenGL/appmanager.h"
#include "aOpenGL/camera.h"
#include "aOpenGL/eigentype.h"
#include "aOpenGL/fbx.h"
#include "aOpenGL/file.h"
#include "aOpenGL/ik.h"
#include "aOpenGL/image.h"
#include "aOpenGL/joint.h"
#include "aOpenGL/light.h"
#include "aOpenGL/material.h"
#include "aOpenGL/mesh.h"
#include "aOpenGL/model.h"
#include "aOpenGL/render.h"
#include "aOpenGL/renderoption.h"
#include "aOpenGL/texture.h"
#include "aOpenGL/util.h"

#include "aOpenGL/kin/kindisp.h"
#include "aOpenGL/kin/kinmodel.h"
#include "aOpenGL/kin/kinmotion.h"
#include "aOpenGL/kin/kinpose.h"

namespace agl = a::gl;